/* Spécifications des schémas : un objet par :::figure.
   layout: flow | layers | grid | hubspoke | cycle
   nodes: [{label, sub?, accent?, soft?}]  (accent=ambre, soft=bleu)
   Les libellés restent courts/techniques (bilingues de fait) ; la légende
   sous la figure porte le détail FR/EN. */
const A = (label, sub) => ({ label, sub, accent: true });
const S = (label, sub) => ({ label, sub, soft: true });
const N = (label, sub) => ({ label, sub });

export const SPECS = [
  // ---------------- Ansible ----------------
  { name: 'ansible-architecture', layout: 'flow', title: 'Architecture sans agent (SSH)',
    nodes: [A('Nœud de contrôle', 'ansible + playbooks'), N('SSH', 'sans agent'), S('Nœuds gérés', 'app1 · app2 · db1')] },
  { name: 'ansible-sysadmin-modules', layout: 'grid', cols: 3, title: 'Catalogue des modules (toujours > command/shell)',
    nodes: [N('Identité', 'group · user'), N('Logiciels', 'apt · dnf'), N('Exécution', 'service · cron'),
      N('Sécurité réseau', 'firewalld · ufw'), N('Stockage', 'lvg · lvol · mount'), A('Idempotent', 'chaque module')] },
  { name: 'ansible-inventory-layout', layout: 'flow', perRow: 4, title: 'Structure d’un projet Ansible',
    nodes: [A('ansible.cfg', 'racine'), N('inventaire', 'à groupes'), N('group_vars/', 'par groupe'), N('host_vars/', 'par hôte')] },
  { name: 'ansible-3tier-architecture', layout: 'flow', title: 'Plateforme 3-tiers pilotée par rôles',
    nodes: [N('Internet'), A('lb1', 'load-balancer'), S('app1 · app2', 'serveurs d’app'), S('db1', 'PostgreSQL')],
    foot: 'chaque tier = un groupe d’inventaire + un rôle ; le LB découvre ses backends via groups/hostvars' },
  { name: 'ansible-role-structure', layout: 'grid', cols: 3, title: 'Anatomie d’un rôle (main.yml auto-chargé)',
    nodes: [N('tasks/', 'le quoi'), N('handlers/', 'réactions'), N('templates/', 'j2'),
      N('files/', 'statiques'), N('defaults/ · vars/', 'variables'), N('meta/', 'dépendances')] },
  { name: 'ansible-flow-control', layout: 'flow', perRow: 4, title: 'Flux d’exécution d’une tâche',
    nodes: [N('loop', 'répète'), N('when', 'filtre'), N('register', 'capture'),
      N('changed/failed_when', 'redéfinit le statut'), N('notify', 'arme un handler'), A('block/rescue/always', 'encadre l’erreur')] },
  { name: 'ansible-var-precedence', layout: 'layers', title: 'Précédence des variables (faible → fort)',
    nodes: [N('role defaults', 'le plus faible'), N('group_vars'), N('host_vars'), N('play vars'), N('task vars'), A('extra-vars  -e', 'gagne toujours')] },
  { name: 'ansible-vault-flow', layout: 'flow', title: 'Cycle Ansible Vault',
    nodes: [S('secrets chiffrés', 'illisibles dans Git'), N('--vault-password-file', 'mot de passe'), A('déchiffré à la volée', 'au moment de jouer'), N('playbook', 'exécuté')] },

  // ---------------- Linux / CLI / Bash ----------------
  { name: 'cli-pipeline', layout: 'flow', title: 'Anatomie d’un pipeline shell',
    nodes: [N('stdin'), A('commandes', 'grep · sort · awk'), N('|  pipe'), N('stdout / > fichier')] },
  { name: 'linux-boot-chain', layout: 'flow', perRow: 5, title: 'Chaîne de démarrage Linux',
    nodes: [N('Firmware', 'BIOS/UEFI'), N('GRUB'), N('Noyau'), A('systemd', 'PID 1'), N('target')],
    foot: 'systemctl gère les units · journalctl lit les logs' },
  { name: 'linux-disk-chain', layout: 'flow', perRow: 4, title: 'Du disque au point de montage',
    nodes: [N('Disque'), N('Partitions'), N('Système de fichiers'), A('Point de montage', 'UUID stable')],
    foot: 'LVM : PV → VG → LV (extension à chaud)' },
  { name: 'linux-filesystem', layout: 'grid', cols: 4, title: 'Arborescence Linux (FHS) — depuis /',
    nodes: [N('/etc', 'config'), N('/var', 'données variables'), N('/home', 'utilisateurs'), N('/usr', 'programmes'),
      N('/bin · /sbin', 'binaires'), N('/tmp', 'temporaire'), N('/dev · /proc', 'système'), N('/srv', 'services')] },
  { name: 'linux-package-levels', layout: 'flow', title: 'Gestion de paquets : deux niveaux',
    nodes: [A('apt / dnf', 'haut niveau · dépôts · dépendances'), N('dpkg / rpm', 'bas niveau · .deb/.rpm · base locale')] },
  { name: 'linux-server-architecture', layout: 'flow', perRow: 4, title: 'Serveur Linux durci & automatisé',
    nodes: [N('Équipe + sudo'), S('volume LVM', '/srv/atelier'), A('service systemd'), N('sauvegarde', 'timer')],
    foot: 'SSH durci + ufw filtrent · provision.sh & healthcheck.sh automatisent' },
  { name: 'linux-network-security', layout: 'grid', cols: 3, title: 'Réseau & sécurité en ligne de commande',
    nodes: [N('ip', 'adresses / routes'), N('ss', 'ports ouverts'), N('DNS', 'résout les noms'),
      N('SSH', 'clés, pas mot de passe'), A('ufw', 'deny par défaut'), N('filtrage entrée', 'pare-feu')] },
  { name: 'linux-bash-script', layout: 'flow', perRow: 4, title: 'Anatomie d’un script Bash',
    nodes: [N('shebang', '#!/bin/bash'), N('variables', 'quoting'), N('arguments', '$1 $#'), N('tests', '[[ ]]'),
      N('conditions', 'if / case'), N('boucles', 'for / while'), N('fonctions'), A('exit code', '0 = ok')] },
  { name: 'linux-permissions', layout: 'flow', title: 'Permissions Linux',
    nodes: [N('rwx', 'propriétaire'), N('rwx', 'groupe'), N('rwx', 'autres'), A('SUID/SGID/sticky', '4ᵉ chiffre'), S('ACL', 'droits fins par user/group')] },

  // ---------------- Git ----------------
  { name: 'git-areas', layout: 'flow', perRow: 4, title: 'Les zones de Git',
    nodes: [N('Répertoire de travail'), N('Staging', 'git add'), N('Dépôt local', 'git commit'), S('Dépôt distant', 'git push')] },

  // ---------------- Docker ----------------
  { name: 'docker-architecture', layout: 'flow', title: 'Architecture Docker',
    nodes: [N('Client', 'docker'), A('Daemon', 'dockerd'), N('Images / Conteneurs'), S('Registry', 'pull / push')] },
  { name: 'docker-multistage', layout: 'flow', title: 'Build multi-stage',
    nodes: [S('Étape build', 'compilateur + sources'), N('binaire'), A('Étape finale', 'copie le binaire seul'), N('image minuscule')] },
  { name: 'docker-networks', layout: 'grid', cols: 3, title: 'Réseaux Docker',
    nodes: [N('bridge défaut', 'IP seulement'), A('bridge utilisateur', 'DNS interne, par nom'), N('host', 'pile de l’hôte'),
      N('none', 'isolé'), N('overlay', 'multi-hôtes'), N('résolution', 'par nom de service')] },
  { name: 'docker-storage', layout: 'grid', cols: 3, title: 'Stockage Docker',
    nodes: [A('Volume nommé', 'géré /var/lib/docker'), N('Bind mount', 'dossier de l’hôte'), N('tmpfs', 'RAM, volatil')],
    foot: 'volume & bind survivent au conteneur ; tmpfs disparaît' },
  { name: 'docker-security', layout: 'layers', title: 'Défense en couches (conteneur)',
    nodes: [N('non-root', 'USER'), N('capabilities minimales'), N('rootfs read-only'), N('limites de ressources'), N('secrets hors ENV'), A('image scannée & signée')] },
  { name: 'docker-swarm', layout: 'flow', title: 'Docker Swarm',
    nodes: [A('Manager', 'état voulu · raft'), N('Services'), S('Tâches', 'réparties sur les nœuds'), N('Routing mesh', 'port publié partout')],
    foot: 'secrets montés en /run/secrets' },
  { name: 'compose-stack', layout: 'flow', title: 'Une stack Docker Compose',
    nodes: [A('compose.yml', 'un seul fichier'), N('services'), N('réseaux'), N('volumes')] },
  { name: 'docker-projet-stack', layout: 'flow', perRow: 4, title: 'Projet : du code à la stack Swarm',
    nodes: [N('Code'), S('image multi-stage', 'durcie'), N('registre local'), A('stack Swarm', 'API ×3 + Redis+volume')],
    foot: 'overlay · secret · rolling update' },

  // ---------------- Homelab / self-host ----------------
  { name: 'homelab-architecture', layout: 'flow', perRow: 5, title: 'Homelab auto-hébergé',
    nodes: [N('Internet'), N('DNS'), N('VPS'), A('reverse proxy', 'HTTPS'), S('services', 'conteneurisés')],
    foot: 'monitorés et sauvegardés' },
  { name: 'immich-architecture', layout: 'flow', perRow: 4, title: 'Architecture Immich',
    nodes: [A('serveur', 'rejoint le réseau proxy'), N('machine learning'), S('PostgreSQL'), S('Redis')] },
  { name: 'monitoring-architecture', layout: 'flow', perRow: 4, title: 'Chaîne de monitoring',
    nodes: [N('exporters'), A('Prometheus', 'scrape + stockage'), S('Grafana', 'dashboards'), N('alertes')] },
  { name: 'cicd-pipeline', layout: 'flow', perRow: 5, title: 'Pipeline CI/CD (workflow)',
    nodes: [N('push'), N('checkout', 'récupère le code'), A('test'), N('build image'), S('publish')] },

  // ---------------- Terraform ----------------
  { name: 'terraform-plan-apply', layout: 'flow', title: 'Cycle plan / apply',
    nodes: [N('code + state + réel'), A('plan', 'diff'), N('apply', 'application')] },
  { name: 'terraform-state-flow', layout: 'flow', title: 'Le state relie code et réel',
    nodes: [N('Code HCL'), A('State', 'la carte'), N('Réel (cloud)'), S('Backend distant', 'partagé + verrouillé')] },
  { name: 'terraform-count-foreach', layout: 'flow', title: 'count vs for_each',
    nodes: [N('count', 'index par position — fragile au retrait'), A('for_each', 'index par clé stable — sûr')] },
  { name: 'terraform-module-interface', layout: 'flow', title: 'Un module = une boîte',
    nodes: [A('variables', 'entrée'), S('ressources', 'cachées à l’intérieur'), N('outputs', 'sortie')],
    foot: 'le module racine appelle des modules enfants' },
  { name: 'terraform-projet-architecture', layout: 'flow', perRow: 4, title: 'Plateforme + environnements',
    nodes: [A('Plateforme', 'réseau partagé'), N('remote state', 'lecture'), S('dev / staging / prod', 'state par env'), N('module stack', 'web+api+db')] },

  // ---------------- Kubernetes ----------------
  { name: 'kubernetes-reconciliation', layout: 'flow', perRow: 4, title: 'Boucle de réconciliation',
    nodes: [A('Deployment'), N('ReplicaSet'), S('Pods'), N('Service', 'expose')],
    foot: 'le contrôleur réconcilie en boucle vers l’état voulu' },
  { name: 'kubernetes-rbac', layout: 'flow', title: 'RBAC Kubernetes',
    nodes: [N('Sujet', 'user / SA'), A('RoleBinding / ClusterRoleBinding'), N('Role (ns) / ClusterRole'), S('auth can-i', 'teste le droit')] },
  { name: 'kubernetes-networking-layers', layout: 'flow', perRow: 4, title: 'Couches réseau K8s',
    nodes: [A('Ingress', 'L7 chemin/hôte'), N('Services', 'IP stable'), N('Endpoints'), S('Pods')],
    foot: 'le DNS nomme les Services · la NetworkPolicy filtre entre pods' },
  { name: 'kubernetes-storage-binding', layout: 'flow', title: 'Liaison du stockage',
    nodes: [S('Pod', 'monte'), A('PVC', 'la demande'), N('PV', 'le disque'), N('StorageClass', 'dynamique')] },
  { name: 'kubernetes-scheduling', layout: 'flow', title: 'Placement des pods',
    nodes: [A('nodeSelector / affinité', 'attire vers nœuds labellisés'), N('taint', 'repousse'), N('toleration', 'sauf ceux qui tolèrent')] },
  { name: 'kubernetes-projet-tiers', layout: 'flow', perRow: 5, title: 'Projet : app 3-tiers',
    nodes: [A('Ingress'), N('Service app'), S('podinfo ×N', 'HPA'), N('Service redis'), S('Redis', 'PVC')],
    foot: 'ConfigMap/Secret alimentent l’app · NetworkPolicy isole Redis' },

  // ---------------- AWS ----------------
  { name: 'aws-ec2-vs-lambda', layout: 'flow', title: 'Deux modèles de compute',
    nodes: [N('EC2', 'VM administrée · continue · payée au temps de fonctionnement'), A('Lambda', 'fonction événementielle · scale 0→N · payée à l’exécution')] },
  { name: 'aws-localstack-setup', layout: 'flow', title: 'Montage local-first (LocalStack)',
    nodes: [N('Ta machine'), N('aws-cli / awslocal'), A('LocalStack', 'Docker :4566'), S('services AWS émulés')],
    foot: 'les mêmes commandes qu’en réel, sans compte ni facture' },
  { name: 'aws-iam-model', layout: 'flow', perRow: 4, title: 'Modèle IAM',
    nodes: [N('Utilisateurs'), N('Groupes'), A('Politiques', 'JSON'), S('Rôle', 'assume-role → creds temporaires')],
    foot: 'évaluation : deny explicite > allow > deny implicite' },
  { name: 'aws-decoupling-fanout', layout: 'flow', title: 'Découplage & fan-out',
    nodes: [N('Producteur'), A('SNS', 'sujet'), S('SQS ×3', 'facturation · expédition · stats'), N('DynamoDB', 'état')],
    foot: 'chaque consommateur traite à son rythme ; un pic s’absorbe dans les files' },
  { name: 'aws-serverless-pipeline', layout: 'flow', perRow: 5, title: 'Pipeline serverless (Terraform)',
    nodes: [A('S3', 'uploads'), N('Lambda', 'processeur'), S('DynamoDB', 'catalogue'), N('SNS', 'notif'), S('SQS', 'aval')] },
  { name: 'aws-vpc-architecture', layout: 'flow', title: 'VPC 10.0.0.0/16',
    nodes: [A('Sous-réseau public', 'route IGW · web + NAT'), N('NAT'), S('Sous-réseau privé', 'sort via NAT · base')],
    foot: 'SG au niveau instance · NACL au niveau sous-réseau' },
  { name: 'aws-s3-lifecycle', layout: 'flow', perRow: 4, title: 'Cycle de vie d’un objet S3',
    nodes: [A('Standard', 'accès fréquent'), N('Standard-IA', '30 j'), S('Glacier', '90 j'), N('Supprimé', '365 j')],
    foot: 'transition automatique selon l’âge et la fréquence d’accès' },
  { name: 'aws-lab-to-real', layout: 'flow', title: 'Du labo au réel (AWS)',
    nodes: [A('LocalStack', 'gratuit · endpoints locaux · IAM non appliqué'), N('bascule Terraform', 'retirer le bloc endpoints'), S('AWS réel', 'facturé · profil IAM · garde-fous coût')] },

  // ---------------- GCP ----------------
  { name: 'gcp-local-lab', layout: 'flow', title: 'Labo GCP local',
    nodes: [N('Ta machine'), N('gcloud & clients'), A('émulateurs', 'Pub/Sub · Datastore'), S('fake-gcs-server', 'Cloud Storage')],
    foot: 'les mêmes commandes/API qu’en réel, sans compte ni facture' },
  { name: 'gcp-iam-terraform', layout: 'flow', perRow: 3, title: 'IAM + Terraform',
    nodes: [N('Principals', 'compte de service'), A('Rôles', 'moindre privilège'), S('Ressources', 'Pub/Sub · Storage')],
    foot: 'init/fmt/validate en local (sans compte) ; plan/apply exigent des identifiants' },
  { name: 'gcp-pubsub-fanout', layout: 'hubspoke', title: 'Pub/Sub en fan-out',
    nodes: [A('Sujet', 'un producteur publie'), S('facturation'), S('email'), S('analytique'), N('dead-letter', 'après N échecs')] },
  { name: 'gcp-storage-choice', layout: 'grid', cols: 3, title: 'Choisir le stockage GCP',
    nodes: [A('Cloud Storage', 'objets · classes par accès'), N('Firestore / Datastore', 'NoSQL structuré'), N('Cloud SQL', 'relationnel')] },
  { name: 'gcp-projet-pipeline', layout: 'flow', perRow: 4, title: 'Plateforme d’ingestion',
    nodes: [A('sujet commandes', 'producteur'), N('abo traitement', 'travailleur'), S('Datastore + archive GCS', 'validation'), N('abo analytique', 'fan-out')],
    foot: 'invalides → dead-letter · Terraform (2 SA moindre privilège) · bootstrap.py rejoue sur émulateurs' },
  { name: 'gcp-lab-to-real', layout: 'flow', title: 'Du labo au réel (GCP)',
    nodes: [A('Émulateurs', 'Pub/Sub · Datastore · fake-gcs · gratuits'), N('pont', 'projet+facturation → auth → budgets → APIs'), S('GCP réel', 'terraform apply → destroy')] },

  // ---------------- Azure AZ-900 / AZ-104 ----------------
  { name: 'azure-lab-local', layout: 'flow', perRow: 4, title: 'Labo Azure local',
    nodes: [N('Ta machine'), N('azlocal · az · Bicep · Terraform'), A('miniblue', 'plan de contrôle ~30 services'), S('Azurite', 'plan de données Blob/Queue/Table')],
    foot: 'Terraform déploie en live contre miniblue — mêmes commandes qu’en réel, sans compte' },
  { name: 'azure-reseau-topologie', layout: 'flow', title: 'Topologie construite (live sur miniblue)',
    nodes: [A('VNet 10.0.0.0/16'), S('web 10.0.1.0/24', 'NSG + IP publique'), S('app 10.0.2.0/24'), S('data 10.0.3.0/24')],
    foot: 'peering vers un spoke + DNS privé en concept · déployé via Terraform' },
  { name: 'azure-stockage-plans', layout: 'flow', title: 'Les deux plans du stockage Azure',
    nodes: [A('Compte de stockage', 'LRS/ZRS/GRS · plan de contrôle (miniblue)'), S('Conteneurs / Blobs', 'niveaux d’accès & de stockage · plan de données (Azurite)')],
    foot: 'SAS expose · cycle de vie (transition/suppression) décrit en Bicep' },
  { name: 'azure-calcul-vm', layout: 'flow', perRow: 4, title: 'Anatomie d’une VM',
    nodes: [N('Taille', 'CPU/RAM'), N('Image', 'OS'), A('Disque OS managé', '± disques data'), S('Carte réseau', 'sous-réseau')],
    foot: 'HA : groupe à haute dispo / zones · élasticité : scale set + autoscale · seul Deallocated arrête le coût calcul' },
  { name: 'azure-rbac-modele', layout: 'flow', title: 'Modèle RBAC (hérite vers le bas)',
    nodes: [N('Principal', 'user · groupe · SP · identité managée'), A('Attribution'), N('Rôle', 'intégré / personnalisé'), S('Portée', 'mg → abo → RG → ressource')],
    foot: 'Policy impose des règles sur une portée · tags & verrous complètent la gouvernance' },
  { name: 'azure-landing-zone', layout: 'flow', perRow: 3, title: 'Zone d’atterrissage (AZ-104)',
    nodes: [A('RÉSEAU', 'VNet hub + sous-réseaux + NSG · Terraform live'), S('CHARGES', 'stockage · identité managée · VM · azlocal'), N('DURCISSEMENT', 'RBAC + policy tag + verrou · Bicep')],
    foot: 'tags communs · appliqué → vérifié → détruit sur miniblue' },
  { name: 'azure-lab-to-real', layout: 'flow', title: 'Du labo au réel (Azure)',
    nodes: [A('miniblue + Azurite', 'émulé · gratuit · sans compte'), N('pont', 'compte+abo → auth → budgets → retirer miniblue'), S('Azure réel', 'terraform apply → destroy')] },

  // ---------------- Azure AZ-305 ----------------
  { name: 'azure-waf-architecture', layout: 'flow', title: 'Architecture multi-tier (Well-Architected)',
    nodes: [A('RÉSEAU', 'web/app/data · NSG'), S('DONNÉES', 'SQL + Redis'), S('COMPUTE', 'Functions / App Service')],
    foot: 'chaque décision éclairée par un pilier : fiabilité · sécurité · coût · exploitation · performance' },
  { name: 'azure-donnees-choix', layout: 'grid', cols: 3, title: 'Choisir le stockage de données Azure',
    nodes: [A('Azure SQL / PostgreSQL', 'relationnel · ACID · jointures'), N('Cosmos DB', 'NoSQL mondial · RU/s'), N('Blob', 'objets / fichiers'),
      N('Cache Redis', 'lecture ultra-rapide'), N('Synapse', 'analytique'), N('Selon la forme', 'de la donnée')] },
  { name: 'azure-infra-compute-reseau', layout: 'flow', title: 'Concevoir l’infrastructure',
    nodes: [N('Front Door', 'global + CDN + WAF'), A('App Gateway', 'L7 + WAF'), S('COMPUTE', 'VM → App Service → Container/AKS → Functions')],
    foot: 'Load Balancer L4 · Traffic Manager DNS · images dans ACR' },
  { name: 'azure-continuite-couches', layout: 'layers', title: 'Trois couches de continuité (réglées par RTO/RPO)',
    nodes: [A('HAUTE DISPONIBILITÉ', 'zones/groupes · panne locale · RTO/RPO ~0'),
      N('SAUVEGARDE', 'coffre Recovery Services + rétention · erreur/corruption'),
      N('REPRISE APRÈS SINISTRE', 'géo-redondance · Site Recovery · perte d’une région')],
    foot: 'plus la cible RTO/RPO est basse, plus le coût monte' },
  { name: 'azure-solution-waf', layout: 'flow', perRow: 3, title: 'Solution Well-Architected (projet AZ-305)',
    nodes: [A('RÉSEAU', 'segmenté · Terraform live'), S('COMPUTE + DONNÉES', 'Container App · SQL + Redis · azlocal live'), N('GOUVERNANCE + CONTINUITÉ', 'RBAC + verrou · sauvegarde + GRS · Bicep')],
    foot: 'chaque tier relié à un pilier WAF · audité par la revue Well-Architected' },

  // ---------------- Azure AZ-400 ----------------
  { name: 'azure-devops-ci-cd', layout: 'flow', title: 'La chaîne DevOps',
    nodes: [N('Branche', 'fonctionnalité'), A('Pull Request', 'revue + checks CI'), N('main', 'fusion'), S('Pipeline', 'CI → CD')],
    foot: 'culture CALMS en socle · mesure en boucle de retour' },
  { name: 'azure-pipelines-cicd-graph', layout: 'flow', perRow: 4, title: 'Pipeline CI/CD en profondeur',
    nodes: [N('lint'), A('test', 'matrice Node 20/22'), N('paquet', 'artefacts'), S('CD', 'porte + déploiement')],
    foot: 'needs/dependsOn dessinent le graphe · le cache accélère sans changer le résultat' },
  { name: 'azure-iac-pipelines-flow', layout: 'flow', perRow: 4, title: 'IaC dans une pipeline',
    nodes: [N('VALIDER', 'fmt + validate'), A('PLAN', 'plan -out=tfplan · artefact'), N('PORTE', 'revue + approbation'), S('APPLY', 'apply tfplan exact')],
    foot: 'état partagé et verrouillé · aucune dérive entre revue et exécution' },
  { name: 'azure-devsecops-chain', layout: 'flow', perRow: 4, title: 'La chaîne DevSecOps (shift-left)',
    nodes: [A('pre-commit', 'bloque les secrets'), S('Key Vault', 'coffre'), N('pipeline sécurité', 'secrets · IaC · deps'), N('moindre privilège', 'actions épinglées SHA')] },
  { name: 'azure-supervision-loop', layout: 'cycle', perRow: 4, title: 'Boucle de supervision',
    nodes: [A('MESURER', '4 métriques DORA'), N('OBSERVER', 'sondes + logs KQL'), N('LIVRER', 'blue-green / canari / flags'), S('ALERTER', 'seuil → notifier / rollback')],
    foot: 'vélocité (2 premières) ET stabilité (2 dernières) ensemble' },
  { name: 'azure-projet-devops-chain', layout: 'flow', perRow: 3, title: 'Chaîne de livraison complète (projet)',
    nodes: [A('SOURCE → SÉCURITÉ', 'branche+PR · hook + checkov'), N('CI → PORTE', 'npm ci + test · approbation'), S('CD → SUPERVISION', 'apply live + Key Vault · smoke test + DORA')],
    foot: 'actions épinglées SHA · moindre privilège · un dépôt, une pipeline, prête pour le CV' },

  // ---------------- Azure AZ-500 ----------------
  { name: 'azure-securite-defense-en-profondeur', layout: 'layers', title: 'Défense en profondeur (Zero Trust)',
    nodes: [A('Identité', 'MFA'), N('Périmètre'), N('Réseau', 'NSG refus par défaut'), N('Calcul'), N('Application'), N('Données', 'chiffrement + coffre')],
    foot: 'vérifier explicitement · moindre privilège · supposer la brèche — boussole CIA' },
  { name: 'azure-securite-identite-flux', layout: 'flow', perRow: 4, title: 'Identité au moindre privilège',
    nodes: [A('Identité managée', 'sans mot de passe'), N('Entra ID', 'jeton'), N('Accès conditionnel', 'MFA · lieu · appareil'), S('RBAC', 'rôle minimal / portée minimale')],
    foot: 'PIM juste-à-temps · revue d’accès retire l’accumulé' },
  { name: 'azure-securite-donnees-couches', layout: 'layers', title: 'Sécurité des données',
    nodes: [A('Classification', 'Public → Secret'), N('Chiffrement au repos', 'défaut → CMK → double couche'), N('Chiffrement en transit', 'TLS 1.2 + HTTPS'), N('Coffre', 'Key Vault + audit'), N('Rotation', 'versions · motif 2 clés')] },
  { name: 'azure-securite-operations-cycle', layout: 'cycle', perRow: 3, title: 'Cycle des opérations de sécurité',
    nodes: [A('GOUVERNER', 'Policy deny + checkov'), N('MESURER', 'Defender · secure score'), N('CENTRALISER', 'Log Analytics'), N('DÉTECTER', 'Sentinel → incidents'), N('CHASSER', 'KQL'), S('RÉPONDRE', 'playbook SOAR')],
    foot: 'la chasse et la réponse nourrissent de nouvelles règles' },
  { name: 'azure-projet-securite-workload', layout: 'flow', perRow: 3, title: 'Workload durci et opéré (projet)',
    nodes: [A('RÉSEAU + IDENTITÉ', 'NSG refus défaut · managée + coffre'), S('DONNÉES + GOUVERNANCE', 'chiffré/TLS · Policy deny + checkov'), N('OPÉRATIONS', 'détection → playbook · secure score')],
    foot: 'cinq piliers AZ-500 superposés · prête pour le CV' },

  // ---------------- Azure AZ-700 ----------------
  { name: 'azure-securite-reseau-segmentation', layout: 'flow', title: 'Sécurité réseau en couches',
    nodes: [N('WAF + rate-limiter', 'entrée : injection/XSS · anti-DDoS'), A('VNet segmenté', 'web → app → data · NSG'), S('Micro-segmentation', 'web ✗ data direct'), N('Egress + endpoint privé', 'FQDN allowlist · PaaS hors Internet')],
    foot: 'NSG : priorité croissante · première règle · refus par défaut' },
  { name: 'azure-reseau-fondamentaux-topologie', layout: 'flow', title: 'Fondations réseau',
    nodes: [A('Espace d’adressage', 'CIDR sans chevauchement'), S('Sous-réseaux', 'web/app/data/gateway · 5 IP réservées'), N('DNS privé', 'app → 10.0.1.10'), N('Hub-and-spoke', 'peering')],
    foot: 'peering seulement si les plages ne se chevauchent pas' },
  { name: 'azure-reseau-routage-selection', layout: 'flow', title: 'Sélection de route Azure',
    nodes: [N('Routes qui matchent'), A('Préfixe le plus long', 'le plus spécifique'), N('Priorité de source', 'UDR > BGP > Système'), S('UDR 0.0.0.0/0', 'tunneling forcé → pare-feu')],
    foot: 'routes effectives = système + BGP + UDR combinées' },
  { name: 'azure-reseau-hybride-connexions', layout: 'grid', cols: 2, title: 'Connectivité hybride — le bon lien',
    nodes: [A('VNet Peering', 'privé · faible latence · non transitif'), N('Gateway transit', 'les spokes empruntent la passerelle du hub'),
      N('VPN Site-to-Site', 'IPsec via Internet · rapide/pas cher'), N('ExpressRoute', 'lien privé dédié · débit garanti · SLA')],
    foot: 'BGP propage les routes dynamiquement' },
  { name: 'azure-reseau-distribution-services', layout: 'grid', cols: 2, title: 'Distribution applicative',
    nodes: [A('Load Balancer', 'L4 · régional · TCP/UDP'), N('Application Gateway', 'L7 · routage chemin + WAF + TLS'),
      N('Front Door', 'L7 global · CDN + WAF'), N('Traffic Manager', 'DNS · dirige vers la région')],
    foot: 'algorithme (round-robin / moindre connexions / hash) + sondes qui excluent les backends KO' },
  { name: 'azure-reseau-acces-prive-privatelink', layout: 'flow', title: 'Accès privé au PaaS',
    nodes: [N('Service public', 'IP publique'), A('Point de terminaison privé', 'IP privée · Private Link'), S('DNS privatelink', 'résout → IP privée'), N('Accès public coupé', 'Disabled')],
    foot: 'alternative légère : point de terminaison de service (IP publique conservée)' },
  { name: 'azure-projet-reseau-topologie', layout: 'flow', perRow: 3, title: 'Topologie complète (projet AZ-700)',
    nodes: [A('ADRESSAGE + HUB/SPOKE', 'hub 10.0/16 · spoke 10.1/16 · peering'), S('ROUTAGE', 'UDR 0.0.0.0/0 → pare-feu du hub'), N('ACCÈS PRIVÉ + DISTRIBUTION', 'endpoint + DNS privatelink · équilibrage')],
    foot: 'cinq piliers AZ-700 sur une seule topologie · prête pour le CV' },
];
